//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class ResourceBundle
{
	int commodity = 0, luxury = 0,  wealth = 0;

	public ResourceBundle (string type, int amount)
	{
		StringAdd (type, amount);
	}

	public ResourceBundle (int _commodities, int _luxuries, int _wealth)
	{
		commodity = _commodities;
		luxury = _luxuries;
		wealth = _wealth;
	}

	void StringAdd (string type, int amount)
	{
		switch (type) {
		case("Commodity"):
			commodity += amount;
			break;
		case("Luxury"):
			luxury += amount;
			break;
		case("Wealth"):
			wealth += amount;
			break;
		default:
			return;
			break;
		}
	}
}


